name: Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'app/**'         # Adjust if your source code lives elsewhere

env:
  IMAGE_NAME: your-dockerhub-username/your-image

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract short SHA
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME:$SHORT_SHA .
        docker push $IMAGE_NAME:$SHORT_SHA

    - name: Update values.yaml with new tag
      run: |
        sed -i "s/tag: .*/tag: $SHORT_SHA/" charts/your-chart/values.yaml

    - name: Commit updated Helm values
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add charts/your-chart/values.yaml
        git commit -m "Update image tag to $SHORT_SHA"
        git push
